namespace TvShowTrackerAPI.Models;

/// <summary>
/// Stores TV show recommendations for users
/// </summary>
public class UserRecommendation : BaseEntity
{
    /// <summary>
    /// Foreign key to User
    /// </summary>
    public Guid UserId { get; set; }

    /// <summary>
    /// Navigation property to User
    /// </summary>
    public User User { get; set; } = null!;

    /// <summary>
    /// Foreign key to recommended TvShow
    /// </summary>
    public Guid TvShowId { get; set; }

    /// <summary>
    /// Navigation property to TvShow
    /// </summary>
    public TvShow TvShow { get; set; } = null!;

    /// <summary>
    /// Recommendation score (0-100)
    /// Higher score = better match for user
    /// Generated by ML algorithm based on:
    /// - User's favorite shows
    /// - Similar users' preferences
    /// - Genre overlap
    /// - Actor overlap
    /// </summary>
    public decimal Score { get; set; }

    /// <summary>
    /// Human-readable reason for recommendation
    /// Example: "Because you liked Breaking Bad"
    /// </summary>
    public string? Reason { get; set; }

    /// <summary>
    /// Whether email notification was sent for this recommendation
    /// </summary>
    public bool EmailSent { get; set; } = false;

    /// <summary>
    /// When the email was sent
    /// </summary>
    public DateTime? EmailSentAt { get; set; }

    /// <summary>
    /// Whether user has viewed this recommendation
    /// </summary>
    public bool IsViewed { get; set; } = false;
}